--【 语音模版 】
-- 如配置modelAlias，对应alias的_assets_model须前行定义
-- 如下面的 Footman

--无语音
_assets_speech('', {
    immovable = { spd = 0, turnRate = 0 },
    building = { isbldg = 1, spd = 0, pathTex = "PathTextures\\4x4SimpleSolid.tga", buildingShadow = "", selCircOnWater = 1, occH = 0, uberSplat = "", canFlee = 0, campaign = 0, collision = 72, hideOnMinimap = 1, canFlee = 0 },
})
--圣骑士
_assets_speech("HeroPaladin")
--大魔法师
_assets_speech("HeroArchMage")
--山丘之王
_assets_speech("HeroMountainKing")
--血魔法师
_assets_speech("HeroBloodElf")
--阿尔塞斯
_assets_speech("Arthas")
--海军上将普洛德摩尔
_assets_speech("Proudmoore")
--吉安娜
_assets_speech("Jaina")
--加理瑟斯
_assets_speech("Garithos")
--追风之西尔瓦娜斯
_assets_speech("Sylvanus")
--火凤凰
_assets_speech("Phoenix")
--剑圣
_assets_speech("HeroBladeMaster")
--地狱咆哮
_assets_speech("Grom")
--先知
_assets_speech("HeroFarSeer")
--萨尔
_assets_speech("Thrall")
--牛头人酋长
_assets_speech("HeroTaurenChieftain")
--暗影猎手
_assets_speech("HeroShadowHunter")
--兽王
_assets_speech("Beastmaster")
--死骑
_assets_speech("HeroDeathKnight")
--巫妖
_assets_speech("HeroLich")
--恐惧魔王
_assets_speech("HeroDreadLord")
--地穴领主
_assets_speech("HeroCryptLord")
--克尔苏加德
_assets_speech("KelthuzadNecro")
--克尔苏加德 (幽灵)
_assets_speech("KelThuzadLich")
--深渊魔王
_assets_speech("PitLord")
--阿克蒙德
_assets_speech("Warlock")
--基尔加丹
_assets_speech("Tichondrius")
--丛林守护者
_assets_speech("HeroKeeperoftheGrove")
--月之女祭司
_assets_speech("HeroMoonPriestess")
--守望者
_assets_speech("herowarden")
--恶魔猎手
_assets_speech("HeroDemonHunter")
--恶魔猎手(邪恶)
_assets_speech("EvilIllidan")
--法里奥
_assets_speech("Furion")
--玛尔法里奥
_assets_speech("MalFurion")
--黑暗游侠
_assets_speech("DarkRanger")
--火焰巨魔
_assets_speech("HeroFireLord")
--炼金术士
_assets_speech("HEROGoblinALCHEMIST")
--美杜莎
_assets_speech("SeaWitch")
--修补匠
_assets_speech("HeroTinker")
--阿卡玛
_assets_speech("Akama")
--熊猫酒仙
_assets_speech("PandarenBrewmaster")
--熊猫大地
_assets_speech("EarthPandarenBrewmaster")
--熊猫雷暴
_assets_speech("StormPandarenBrewmaster")
--熊猫烈焰
_assets_speech("FirePandarenBrewmaster")
--农民
_assets_speech("Peasant")
--步兵
_assets_speech("Footman", {
    avatar = _assets_speech_extra({ modelAlias = "Footman" })
})
--骑士
_assets_speech("Knight", {
    avatar = _assets_speech_extra({ modelAlias = "Knight" })
})
--矮人火枪手
_assets_speech("Rifleman")
--迫击炮小队
_assets_speech("MortarTeam")
--飞行机器
_assets_speech("Gyrocopter")
--狮鹫骑士
_assets_speech("GryphonRider")
--牧师
_assets_speech("Priest")
--女巫
_assets_speech("Sorceress")
--蒸汽机车
_assets_speech("SteamTank")
--魔法破坏者
_assets_speech("SpellBreaker")
--龙鹰骑士
_assets_speech("BloodElfDragonHawk")
--水元素
_assets_speech("WaterElemental")
--剑士
_assets_speech("HighElfSwordsman")
--牧师使者
_assets_speech("HumanMage")
--高级精灵男
_assets_speech("BloodElfWorker")
--麦迪文
_assets_speech("Medivh")
--苦工
_assets_speech("Peon")
--兽族步兵
_assets_speech("Grunt")
--兽族步兵(邪恶)
_assets_speech("ChaosGrunt")
--掠夺者
_assets_speech("WolfRider")
--牛头人
_assets_speech("Tauren")
--巨魔猎头者
_assets_speech("HeadHunter")
--粉碎者
_assets_speech("Catapult")
--科多兽
_assets_speech("KotoBeast")
--科多兽(无驾驶员)
_assets_speech("KotoBeastNoRider")
--风骑士
_assets_speech("WyvernRider")
--巨魔蝙蝠骑士
_assets_speech("TrollBatrider")
--巨魔萨满
_assets_speech("WitchDoctor")
--萨满
_assets_speech("Shaman")
--灵魂行者
_assets_speech("SpiritWalker")
--幽魂之狼
_assets_speech("SpiritWolf")
--毒蛇守卫
_assets_speech("SerpentWard")
--岗哨守卫
_assets_speech("SentryWard")
--静止陷阱
_assets_speech("StasisTotem")
--治疗守卫
_assets_speech("HealingWard")
--兽族战争首领
_assets_speech("ChaosWarlord")
--德拉克苏尔
_assets_speech("ShamanX")
--侍僧
_assets_speech("Acolyte")
--阴影
_assets_speech("Shade")
--食尸鬼
_assets_speech("Ghoul")
--憎恶
_assets_speech("Abomination")
--绞肉车
_assets_speech("MeatWagon")
--穴居恶魔
_assets_speech("CryptFiend")
--石像鬼
_assets_speech("Gargoyle")
--女妖
_assets_speech("Banshee")
--女妖(灵魂)
_assets_speech("BansheeGhost")
--不死族巫师
_assets_speech("Necromancer")
--十胜石雕像
_assets_speech("ObsidianStatue")
--冰霜巨龙
_assets_speech("FrostWyrm")
--蝗虫
_assets_speech("Locust")
--疾病云雾
_assets_speech("PlagueCloud")
--骷髅战兵
_assets_speech("Skeleton")
--骷髅弓箭手
_assets_speech("SkeletonArcher")
--腐尸甲虫
_assets_speech("Scarab")
--僵尸
_assets_speech("Zombie")
--小精灵
_assets_speech("Wisp")
--弓箭手
_assets_speech("Archer")
--女猎手
_assets_speech("Huntress")
--树妖
_assets_speech("Dryad")
--投刃车
_assets_speech("Ballista")
--角鹰兽
_assets_speech("Hippogryph")
--角鹰兽骑士
_assets_speech("RiddenHippogryph")
--奇美拉
_assets_speech("Chimaera")
--猛禽德鲁伊
_assets_speech("DruidoftheTalon")
--利爪德鲁伊
_assets_speech("DruidoftheClaw")
--山岭巨人
_assets_speech("MountainGiant")
--精灵龙
_assets_speech("FaerieDragon")
--猫头鹰侦察者
_assets_speech("owl")
--树人
_assets_speech("Ent")
--复仇天神
_assets_speech("SpiritOfVengeance")
--复仇之魂
_assets_speech("Vengeance")
--守望者(暗杀)
_assets_speech("Assassin")
--飞蛇
_assets_speech("WindSerpent")
--娜迦海妖
_assets_speech("NagaSiren")
--飞龙
_assets_speech("SnapDragon")
--娜迦暴徒
_assets_speech("NagaMyrmidon")
--娜迦皇家卫兵
_assets_speech("NagaRoyalGuard")
--口袋工厂
_assets_speech("PocketFactory")
--口袋工厂(人工地精)
_assets_speech("ClockwerkGoblin")
--炎魔
_assets_speech("LavaSpawn")
--米纱熊
_assets_speech("GrizzlyBear")
--战鹰
_assets_speech("WarEagle")
--海龟
_assets_speech("GiantSeaTurtle")
--小鱼人
_assets_speech("Murloc")
--龙
_assets_speech("AzureDragon")
--耐瑟龙
_assets_speech("NetherDragon")
--小蜘蛛
_assets_speech("Spider")
--蛛网怪
_assets_speech("Nerubian")
--鹰女妖
_assets_speech("Harpy")
--虚空假面(红)
_assets_speech("Unbroken")
--虚空假面(紫)
_assets_speech("ObsidianDestroyer")
--地狱火
_assets_speech("Infernal")
--毁灭守卫
_assets_speech("DoomGuard")
--刺蛇
_assets_speech("Hydralisk")
--灵兽
_assets_speech("Felhound")
--淤泥怪
_assets_speech("SludgeMonster")
--岩石傀儡
_assets_speech("RockGolem")
--灵肉傀儡
_assets_speech("abomination")
--阿卡那瑟德蝎子
_assets_speech("Archnathid")
--强盗
_assets_speech("Bandit")
--龙卵战士
_assets_speech("DragonSpawn")
--半人马战士
_assets_speech("Centaur")
--半人马弓箭手
_assets_speech("CentaurArcher")
--森林巨魔
_assets_speech("ForestTroll")
--森林巨魔牧师
_assets_speech("ForestTrollShadowPriest")
--冰原巨魔战士
_assets_speech("IceTroll")
--冰原巨魔牧师
_assets_speech("IceTrollShadowPriest")
--熊怪
_assets_speech("Furbolg")
--深海巨猎人
_assets_speech("SeaGiant")
--豺狼
_assets_speech("Gnoll")
--豺狼猎手
_assets_speech("GnollArcher")
--狗头人
_assets_speech("Kobold")
--巨虾
_assets_speech("Lobstrokk")
--猛犸
_assets_speech("Mammoth")
--玛格战士
_assets_speech("Magnataur")
--食人鬼
_assets_speech("Ogre")
--鹰嘴野兽
_assets_speech("Owlbear")
--豪猪
_assets_speech("Bristleback")
--死亡幽魂
_assets_speech("Revenant")
--赛特斯地狱使者
_assets_speech("Satyr")
--女妖精
_assets_speech("Demoness")
--图斯卡
_assets_speech("Tuskarr")
--野人
_assets_speech("Wendigo")
--海豹
_assets_speech("Seal")
--浣熊
_assets_speech("Raccoon")
--老鼠
_assets_speech("Rat")
--绵羊
_assets_speech("Sheep")
--企鹅
_assets_speech("Penguin")
--青蛙
_assets_speech("Frog")
--秃鹰
_assets_speech("Vulture")
--兔子
_assets_speech("Rabbit")
--小鸡
_assets_speech("Chicken")
--小蜥蜴
_assets_speech("Skink")
--信天翁
_assets_speech("Albatross")
--雪鹰
_assets_speech("SnowOwl")
--鬃狼
_assets_speech("Wolf")
--豪猪
_assets_speech("QuillBeast")
--野猪
_assets_speech("Pig")
--虫族小狗
_assets_speech("Zergling")
--船
_assets_speech("Boat")
--囚车
_assets_speech("PrisonWagon")
--地狱机关人
_assets_speech("InfernalMachine")
--地精地雷
_assets_speech("GoblinLandMine")
--地精飞艇
_assets_speech("GoblinZeppelin")
--地精工兵
_assets_speech("GoblinSapper")
--地精撕裂者
_assets_speech("IronGolem")
--马里恩(冲锋枪小哥)
_assets_speech("TerranMarine")
--邪恶空间兽人(冲锋枪兽人)
_assets_speech("ChaosSpaceOrc")
--村民男1
_assets_speech("VillagerMan")
--村民男2
_assets_speech("VillagerMan2")
--村民女1
_assets_speech("VillagerWoman")
--村民小孩
_assets_speech("VillagerKid")